name: ecpp

on:
  pull_request:
    paths-ignore:
      - README.md
      - SECURITY.md
      - LICENSE-APACHE
      - LICENSE-MIT
      - .pants-ignore
      - rustfmt.toml
  push:
    branches: main
    paths-ignore:
      - README.md
      - SECURITY.md
      - LICENSE-APACHE
      - LICENSE-MIT
      - .pants-ignore
      - rustfmt.toml

env:
  CARGO_INCREMENTAL: 0
  CARGO_TERM_COLOR: always
  RUST_LOG_STYLE: always
  RUSTFLAGS: "-Dwarnings"
  RUSTDOCFLAGS: "-Dwarnings"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo build --no-default-features
      - run: cargo build --no-default-features --features=alloc
      - run: cargo build --no-default-features --features=crypto-bigint
      - run: cargo build --no-default-features --features=num-bigint
      - run: cargo build --no-default-features --features=rug
      - run: cargo build --no-default-features --features=openssl
      - run: cargo build --all-features

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: all features
            arguments: --all-features
          - name: fixed crypto-bigint
            arguments: --no-default-features --features=crypto-bigint
          - name: heap crypto-bigint
            arguments: --no-default-features --features=alloc,getrandom,crypto-bigint
          - name: num-bigint
            arguments: --no-default-features --features=getrandom,num-bigint
          - name: rug
            arguments: --no-default-features --features=getrandom,rug
          - name: OpenSSL
            arguments: --no-default-features --features=getrandom,openssl
    name: test (${{ matrix.name }})
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo test ${{ matrix.arguments }} --release

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - uses: taiki-e/install-action@cargo-llvm-cov
      - run: cargo llvm-cov --all-features --workspace --lcov --output-path lcov.info
      - uses: codecov/codecov-action@v7
        with:
          files: lcov.info

  careful:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-careful
      - run: cargo +nightly careful test --no-default-features --features=alloc,num-bigint
      - run: cargo +nightly careful test --no-default-features --features=crypto-bigint

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - run: cargo clippy --all-targets --no-default-features --features=crypto-bigint -- -D warnings

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: rustfmt
      - run: cargo fmt --all -- --check

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
      - run: cargo doc --no-deps --all-features

  deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-udeps
      - run: cargo +nightly udeps --all-targets --all-features

  outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-outdated
      - run: cargo outdated --root-deps-only --exit-code 1

  pants:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
      - uses: cargo-bins/cargo-binstall@main
      - run: cargo binstall --no-confirm cargo-pants
      - run: cargo pants --loud --dev
